export type IconNames =
   | 'Github'
   | 'EmailPlus'
   | 'EmailLock'
   | 'Success'
   | 'X'
   | 'LinkedIn'
   | 'Youtube'
   | 'Close'
   | 'ArrowDown'
   | 'ArrowRight'
   | 'FastFood'
   | 'CodeSquare'
   | 'NextJs'
   | 'Typescript'
   | 'Mdx'
   | 'TailwindCSS'
   | 'Firebase'
   | 'LinkIcon'
   | 'RadixUi'
   | 'ReactQuery'
   | 'Galery'
   | 'AlertIcon'
   | 'PlanetScale'
   | 'MongoDb'
   | 'Figma'
   | 'AffinityDesigner'
   | 'Sketch'
   | 'Framer'
   | 'React'
   | 'Wordpress'

export type IconSizes = 'xs' | 'sm' | 'md' | 'lg' | 'xl'