export type IconNames =
   | 'Github'
   | 'EmailPlus'
   | 'EmailLock'
   | 'Success'
   | 'X'
   | 'LinkedIn'
   | 'Youtube'
   | 'Close'
   | 'ArrowDown'
   | 'ArrowRight'
   | 'FastFood'
   | 'CodeSquare'
   | 'NextJs'
   | 'Typescript'
   | 'Mdx'
   | 'TailwindCSS'
   | 'Firebase'
   | 'LinkIcon'
   | 'RadixUi'
   | 'ReactQuery'
   | 'Galery'
   | 'AlertIcon'
   | 'PlanetScale'

export type IconSizes = 'xs' | 'sm' | 'md' | 'lg' | 'xl'